import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>The Dons</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-4xl text-center">The Dons</h1>
    </>
  )
}
