import Head from 'next/head'
import Nav from '../components/nav'

const Roadmap = () => {
  return (
    <>
      <Head>
        <title>The Dons</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen h-full min-h-screen text-xl bg-center bg-cover bg-dons-white font-dons-altona text-dons-black">
        <Nav active="roadmap" />

        <div className="container px-4 pt-12 pb-8 mx-auto">
          <div className="lg:w-2/5">
            <h1 className="text-6xl font-dons-jungle">Roadmap</h1>
            <p className="mt-4 leading-relaxed">
              Our roadmap shows what we are currently working on and ready to
              share. We have a lot of exciting things in store that are not
              ready for announcement just yet and we are always looking to add
              new value.
            </p>
          </div>

          <a href="/img/roadmap.jpg">
            <img src="/img/roadmap.jpg" alt="The Roadmap" className="my-8" />
          </a>
        </div>
      </div>
    </>
  )
}

export default Roadmap
